/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as ImportExcelRouteImport } from './routes/import-excel'
import { Route as FaceVerifyRouteImport } from './routes/face-verify'
import { Route as DepensesRouteImport } from './routes/depenses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExcelRoute = ImportExcelRouteImport.update({
  id: '/import-excel',
  path: '/import-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaceVerifyRoute = FaceVerifyRouteImport.update({
  id: '/face-verify',
  path: '/face-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DepensesRoute = DepensesRouteImport.update({
  id: '/depenses',
  path: '/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/depenses': typeof DepensesRoute
  '/face-verify': typeof FaceVerifyRoute
  '/import-excel': typeof ImportExcelRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/students': typeof StudentsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/depenses': typeof DepensesRoute
  '/face-verify': typeof FaceVerifyRoute
  '/import-excel': typeof ImportExcelRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/students': typeof StudentsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/dashboard': typeof DashboardRoute
  '/depenses': typeof DepensesRoute
  '/face-verify': typeof FaceVerifyRoute
  '/import-excel': typeof ImportExcelRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/students': typeof StudentsRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/dashboard'
    | '/depenses'
    | '/face-verify'
    | '/import-excel'
    | '/import-export'
    | '/login'
    | '/students'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes'
    | '/dashboard'
    | '/depenses'
    | '/face-verify'
    | '/import-excel'
    | '/import-export'
    | '/login'
    | '/students'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/classes'
    | '/dashboard'
    | '/depenses'
    | '/face-verify'
    | '/import-excel'
    | '/import-export'
    | '/login'
    | '/students'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  DashboardRoute: typeof DashboardRoute
  DepensesRoute: typeof DepensesRoute
  FaceVerifyRoute: typeof FaceVerifyRoute
  ImportExcelRoute: typeof ImportExcelRoute
  ImportExportRoute: typeof ImportExportRoute
  LoginRoute: typeof LoginRoute
  StudentsRoute: typeof StudentsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-excel': {
      id: '/import-excel'
      path: '/import-excel'
      fullPath: '/import-excel'
      preLoaderRoute: typeof ImportExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-verify': {
      id: '/face-verify'
      path: '/face-verify'
      fullPath: '/face-verify'
      preLoaderRoute: typeof FaceVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depenses': {
      id: '/depenses'
      path: '/depenses'
      fullPath: '/depenses'
      preLoaderRoute: typeof DepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  DashboardRoute: DashboardRoute,
  DepensesRoute: DepensesRoute,
  FaceVerifyRoute: FaceVerifyRoute,
  ImportExcelRoute: ImportExcelRoute,
  ImportExportRoute: ImportExportRoute,
  LoginRoute: LoginRoute,
  StudentsRoute: StudentsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
